### ISSUE TITLE
How to display the value on or above a bar?

### ISSUE THREAD

**Issue by shlomogoldstein** [gruberb/chartistAngularDirective#3]
I want to display the value of a bar permanently on the bar itself or on top. How can I achieve this? It should not interfere with the tool tip functionality. I am using a stacked bar, so this should work for each bar part.

**Comment by gruberb** [comment]
Sorry, I don't understand why GitHub doesn't notify on new Issues. Just reading this now. Do you still need support?

**Comment by shlomogoldstein** [comment]
No thank you I managed to solve it.
